#!/bin/bash


echo "Content-type: text/html"
echo ""

echo "<!DOCTYPE html>"
echo "<html>"
echo "<head>"
echo "<title>POST Request</title>"
echo "<style>"
echo "body {"
echo "  display: flex;"
echo "  justify-content: center;"
echo "  align-items: center;"
echo "  height: 100vh;"
echo "  font-family: Arial, sans-serif;"
echo "}"
echo "div {"
echo "  text-align: center;"
echo "}"
echo "</style>"
echo "</head>"
echo "<body>"
echo "<div>"
echo "<h1>POST Request Received</h1>"
echo "<h2>CGI Script is Working</h2>"
echo "<h3>Request Method: $(echo $REQUEST_METHOD)</h3>"
echo "<h3>Server Protocol: $(echo $SERVER_PROTOCOL)</h3>"
echo "<h3>Content Length: $(echo $CONTENT_LENGTH)</h3>"
echo "<h3>Server Name: $(echo $SERVER_NAME)</h3>"
echo "<h3>Server Port: $(echo $SERVER_PORT)</h3>"
echo "</div>"
echo "</body>"
echo "</html>"